[package]
name = "zed_mojo"
version = "0.1.0"
edition = "2021"
publish = false
license = "Apache-2.0"

[lib]
path = "src/lib.rs"
crate-type = ["cdylib"]

[dependencies]
ruzstd = "0.9.0"
sha2 = "0.11.0"
tar = { version = "0.4.46", default-features = false }
zed_extension_api = "0.7.0"
zip = { version = "2.4.2", default-features = false }

[dev-dependencies]
tempfile = "3.23.0"
zstd = "0.13.3"
